name: "[DEV]Deploy Azure Policies"
on:
  push:
    branches:
      - dev
    paths:
      - "initiatives/**"
      - "policies/**"
      - ".github/workflows/deploy-azurepolicies.yml"
      - "scripts/AzurePolicy.ps1"
  workflow_dispatch:

jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Create tmp folder
        shell: bash
        run: |
          mkdir tmp

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_SP}}
          enable-AzPSSession: true

      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          inlineScript: ./scripts/AzurePolicy.ps1 -scopeType "subscriptions" -scope "/subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}"
          azPSVersion: "latest"
          errorActionPreference: continue
