name: 'Deploy Azure Policies'
on:
  push:
    branches:
      - main
    paths:
      - 'policies/**'
      - '.github/workflows/deploy-azurepolicies.yml'
      - 'scripts/AzurePolicy.ps1'
  workflow_dispatch:
  pull_request:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - run: |
        mkdir tmp
        ls -ltr
      shell: bash

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_SP}}
        enable-AzPSSession: true 

    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: ./scripts/AzurePolicy.ps1 -scopeType "subscriptions" -scope "/subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}"
        azPSVersion: "latest"
        errorActionPreference: continue