
name: 'Terraform Deploy'
on:
  push:
    branches:
      - main
    paths:
      - "terraform-live/**"
  pull_request:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  plan:
    name: "Plan Job"
    strategy:
      matrix:
        stage: [dev]
    runs-on: ubuntu-latest
    defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./terraform-live
    concurrency: ${{ matrix.stage }}
    steps:
    - uses: actions/checkout@v3

    - uses: jungwinter/split@v2
      id: split
      with:
        msg: ${{ github.repository }}
        separator: "/"

    - uses: "./.github/actions/azure-backend"
      with:
        AZURE_SP: ${{ secrets.AZURE_SP }}
        RESOURCE_GROUP_NAME: "policy-as-code-tfstate-${{ matrix.stage }}-rg"
        RESOURCE_GROUP_LOCATION: "eastus"
        TAGS: '"UseCase=Terraform" "Stage=${{ github.job }}" "Deployed=GitHub Actions" Repository=${{ steps.split.outputs._1 }} "RunNumber=${{ github.run_number }}"'
        STORAGE_ACCOUNT_NAME: "stacpolicyascode${{ matrix.stage }}"

    - uses: "./.github/actions/terraform-plan"
      with:
        WORKING_DIR: "."
        AZURE_SP: ${{ secrets.AZURE_SP }}
        RESOURCE_GROUP_NAME: "policy-as-code-tfstate-${{ matrix.stage }}-rg"
        STORAGE_ACCOUNT_NAME: "stacpolicyascode${{ matrix.stage }}"
        CONTAINER_NAME: "states"
        STATE_FILE: "policy-as-code.tfstate"
        STAGE: "${{ matrix.stage }}"

  apply:
    name: "Apply Job"
    needs: plan
    strategy:
      matrix:
        stage: [dev]
    runs-on: ubuntu-latest
    defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./terraform-live
    steps:
    - uses: actions/checkout@v3

    - uses: "./.github/actions/terraform-apply"
      with:
        WORKING_DIR: "."
        AZURE_SP: ${{ secrets.AZURE_SP }}
        STORAGE_ACCOUNT_NAME: "stacpolicyascode${{ matrix.stage }}"
        STAGE: "${{ matrix.stage }}"