name: "Terraform Deploy"
on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  plan:
    name: "Terraform"
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        stage: [dev]
    concurrency: ${{ matrix.stage }}
    uses: leomozzer/terraform-template/.github/workflows/terraform-plan.yml@main
    with:
      TERRAFORM_WORKING_DIR: "terraform-live"
      TERRAFORM_MODULES_DIR: "terraform-modules"
      WORKING_DIR: "./"
      RESOURCE_GROUP_NAME: "policy-as-code-tfstate-${{ matrix.stage }}-rg"
      RESOURCE_GROUP_LOCATION: "eastus"
      STORAGE_ACCOUNT_NAME: "stacpolicyascode${{ matrix.stage }}"
      CONTAINER_NAME: "states"
      STATE_FILE: "policy-as-code.tfstate"
      STAGE: ${{ matrix.stage }}
      TAGS: '"UseCase=Terraform" "Environment=${{ matrix.stage }}" "Deployed=GitHub Actions" Repository="https://github.com/leomozzer/policy-as-code" "RunNumber=${{ github.run_number }}" "MaintainedBy=leomozzer"'
    secrets:
      AZURE_SP: ${{ secrets.AZURE_SP }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  apply:
    name: "Terraform"
    needs: plan
    strategy:
      matrix:
        stage: [dev]
    concurrency: ${{ matrix.stage }}
    uses: leomozzer/terraform-template/.github/workflows/terraform-apply.yml@main
    with:
      WORKING_DIR: "./"
      STORAGE_ACCOUNT_NAME: "stacpolicyascode${{ matrix.stage }}"
      CONTAINER_NAME: "plans"
      STAGE: ${{ matrix.stage }}
    secrets:
      AZURE_SP: ${{ secrets.AZURE_SP }}

  stac:
    name: "Keep min tf plan files"
    needs: apply
    strategy:
      matrix:
        stage: [dev]
    runs-on: ubuntu-latest
    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_SP}}
          enable-AzPSSession: true

      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          inlineScript: ./scripts/CleanPlanContainer.ps1 -resourceGroupName "policy-as-code-tfstate-${{ matrix.stage }}-rg" -storageAccountName "stacpolicyascode${{ matrix.stage }}" -containerName "plans" -maximumTerraformPlanFiles 1 -getTerraformModules $true
          azPSVersion: "latest"
          errorActionPreference: continue
