
name: 'Terraform Deploy'
on:
  workflow_run:
    workflows: ["Audit Terraform"]
    branches: [main]
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - 'terraform-live/**'
      - 'terraform-modules/**'
      - 'policies/**'
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  check:
    name: Check modified files
    outputs:
      run_job: ${{ steps.check_file_changed.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under terraform-live/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match '^terraform-live/' -or $_ -match '.md$' -or $_ -match '^terraform-modules/' -or $_ -match '^policies/'}
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "docs_changed"
        Write-Host "::set-output name=run_job::$HasDiff"

  plan:
    name: "Plan Job"
    needs: [check]
    if: needs.check.outputs.run_job == 'true' && ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        stage: [dev]
    runs-on: ubuntu-latest
    defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./terraform-live
    concurrency: ${{ matrix.stage }}
    steps:
    - uses: actions/checkout@v3

    - uses: jungwinter/split@v2
      id: split
      with:
        msg: ${{ github.repository }}
        separator: "/"

    - uses: "./.github/actions/azure-backend"
      with:
        AZURE_SP: ${{ secrets.AZURE_SP }}
        RESOURCE_GROUP_NAME: "policy-as-code-tfstate-${{ matrix.stage }}-rg"
        RESOURCE_GROUP_LOCATION: "eastus"
        TAGS: '"UseCase=Terraform" "Stage=${{ github.job }}" "Deployed=GitHub Actions" Repository=${{ steps.split.outputs._1 }} "RunNumber=${{ github.run_number }}"'
        STORAGE_ACCOUNT_NAME: "stacpolicyascode${{ matrix.stage }}"

    - uses: "./.github/actions/terraform-plan"
      with:
        WORKING_DIR: "."
        AZURE_SP: ${{ secrets.AZURE_SP }}
        RESOURCE_GROUP_NAME: "policy-as-code-tfstate-${{ matrix.stage }}-rg"
        STORAGE_ACCOUNT_NAME: "stacpolicyascode${{ matrix.stage }}"
        CONTAINER_NAME: "states"
        STATE_FILE: "policy-as-code.tfstate"
        STAGE: "${{ matrix.stage }}"

  apply:
    name: "Apply Job"
    needs: plan
    strategy:
      matrix:
        stage: [dev]
    runs-on: ubuntu-latest
    defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./terraform-live
    steps:
    - uses: actions/checkout@v3

    - uses: "./.github/actions/terraform-apply"
      with:
        WORKING_DIR: "."
        AZURE_SP: ${{ secrets.AZURE_SP }}
        STORAGE_ACCOUNT_NAME: "stacpolicyascode${{ matrix.stage }}"
        STAGE: "${{ matrix.stage }}"