name: "Terraform Deploy"
on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  audit:
    name: "Audit"
    permissions:
      contents: read
      pull-requests: write
    uses: leomozzer/terraform-template/.github/workflows/audit.yml@main
    with:
      TERRAFORM_WORKING_DIR: "terraform-live"
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

  plan:
    name: "Terraform"
    needs: audit
    strategy:
      matrix:
        stage: [dev]
    concurrency: ${{ matrix.stage }}
    uses: leomozzer/terraform-template/.github/workflows/terraform-plan.yml@main
    with:
      TERRAFORM_WORKING_DIR: "terraform-live"
      TERRAFORM_MODULES_DIR: "terraform-modules"
      WORKING_DIR: "./"
      RESOURCE_GROUP_NAME: "policy-as-code-tfstate-${{ matrix.stage }}-rg"
      RESOURCE_GROUP_LOCATION: "eastus"
      STORAGE_ACCOUNT_NAME: "stacpolicyascode${{ matrix.stage }}"
      CONTAINER_NAME: "states"
      STATE_FILE: "policy-as-code.tfstate"
      STAGE: ${{ matrix.stage }}
      TAGS: '"UseCase=Terraform" "Environment=${{ matrix.stage }}" "Deployed=GitHub Actions" Repository="https://github.com/leomozzer/policy-as-code" "RunNumber=${{ github.run_number }}" "MaintainedBy=leomozzer"'
    secrets:
      AZURE_SP: ${{ secrets.AZURE_SP }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  apply:
    name: "Terraform"
    needs: plan
    strategy:
      matrix:
        stage: [dev]
    concurrency: ${{ matrix.stage }}
    uses: leomozzer/terraform-template/.github/workflows/terraform-apply.yml@main
    with:
      WORKING_DIR: "./"
      STORAGE_ACCOUNT_NAME: "stacpolicyascode${{ matrix.stage }}"
      CONTAINER_NAME: "plans"
      STAGE: ${{ matrix.stage }}
    secrets:
      AZURE_SP: ${{ secrets.AZURE_SP }}

  # stac:
  #   name: "Keep min tf plan files"
  #   needs: apply
  #   strategy:
  #     matrix:
  #       stage: [dev]
  #   concurrency: ${{ matrix.stage }}
  #   uses: leomozzer/terraform-template/.github/workflows/terraform-files-lifecycle.yml@main
  #   with:
  #     RESOURCE_GROUP_NAME: "policy-as-code-tfstate-${{ matrix.stage }}-rg"
  #     STORAGE_ACCOUNT_NAME: "stacpolicyascode${{ matrix.stage }}"
  #     CONTAINER_NAME: "plans"
  #     MAXIMUM_TERRAFORM_PLAN_FILES: 1
  #     GET_TERRAFORM_MODULES: true
  #   secrets:
  #     AZURE_SP: ${{ secrets.AZURE_SP }}
